### ISSUE TITLE
Summer Course on Computational Neuroscience (DL: June 24, 2017)

### ISSUE THREAD

**Issue by sonamsingh19** [PhABC/neuroSummerSchools#4]
This one on web is for 2016. Is this for 2017 too? Couldn't find the appropriate info.
http://www.bccn-goettingen.de/events/cns-course
Thanks for the list.

**Comment by PhABC** [comment]
I found this ; https://www.ntnu.edu/documents/21631968/0/2017+Summer+School+NTNU/6a6987ca-aeba-4294-a762-354a022c19b4

Will add it to the list, thanks!
